### ISSUE TITLE
你好，可以分享一下比赛用的数据吗

### ISSUE THREAD

**Issue by chongababa** [xwen99/CCF-BDCI-VideoCopyDetection#1]
你好，可以分享一下比赛用的数据吗，现在不能报名下载了，非常感谢！

**Comment by xwen99** [comment]
> 你好，可以分享一下比赛用的数据吗，现在不能报名下载了，非常感谢！

请尝试以下链接：
http://datafountain.int-yt.com/BDCI2019/AiQiYI/train.csv
http://datafountain.int-yt.com/BDCI2019/AiQiYI/train_query.tar.gz
http://datafountain.int-yt.com/BDCI2019/AiQiYI/train_refer.tar.gz
http://datafountain.int-yt.com/BDCI2019/AiQiYI/test_query.tar.gz
http://datafountain.int-yt.com/BDCI2019/AiQiYI/submit_example.csv

**Comment by chongababa** [comment]
可以下载，非常感谢！

**Comment by splinter21** [comment]
@xwen99 hi！想请教下比赛的时候数据集是怎么分配的，
现在下到3个视频包，train有3k查询+205refer，test只有query1k5
但是我看比赛答辩论文里面有说1k6查询200refer的，所以比较好奇…
以及比赛复赛有更新数据集吗？
