### ISSUE TITLE
Do you have ideas how to improve? 

### ISSUE THREAD

**Issue by wjtan99** [xwen99/CCF-BDCI-VideoCopyDetection#2]
Thanks a lot for your nice work.  Do you have ideas how to further improve the max F1 score? I notice the first a few winners achieved around or greater than 0.9.

**Comment by DTennant** [comment]
Maybe you can try using reranking for the retrieval https://github.com/zhunzhong07/person-re-ranking, we have this idea, but do not have the time to implement this during the competition.

**Comment by xwen99** [comment]
Thank you for your approval :). As far as I can see, direct improvement can be reached with better frame-level feature representation(unsupervised approaches like aggregating CNN features from multi-layers, supervised approached like metric learning, NetVLAD, etc.), you can refer to the Youtube-8M contest. Besides, time alignment is also an important part of this model, maybe you can find a more efficient way other than my graph-based approach. To reach a high recall with global features and then re-rank the top-k instances with local features, namely reranking mentioned by @DTennant  is a common approach used in retrieval tasks, maybe you will find it helpful. By the way, the top 5 solutions of this contest can be found here: [link](https://discussion.datafountain.cn/questions/2236).

**Comment by wjtan99** [comment]
@xwen99 @DTennant Thanks a lot for your quick response.  Both are very helpful.
